### ISSUE TITLE
Trouble using the example for cl-lexer

### ISSUE THREAD

**Issue by mgcheung** [starseeker/cl-lexer#1]
I am trying to use cl-lexer and when I tried writing my own example, I was getting some errors.  I installed using quicklisp, first directly and then I cloned the git repo.  Either way, the following shows what happens when I try to run the example.lisp file.  Is there some dependency I'm missing?  Thanks.

$ sbcl
This is SBCL 1.0.55.0.debian, an implementation of ANSI Common Lisp.
More information about SBCL is available at http://www.sbcl.org/.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.
- (load "quicklisp/local-projects/cl-lexer/example")

; file: /home/mgcheung/quicklisp/local-projects/cl-lexer/example.lisp
; in: DEFLEXER TEST-LEXER
;     (LEXER:DEFLEXER TEST-LEXER::TEST-LEXER
;                     ("[0-9]+([.][0-9]+([Ee][0-9]+)?)"
;                      (RETURN (VALUES 'TEST-LEXER::FLT (LEXER:NUM LEXER:%0))))
;                     ("[0-9]+" (RETURN (VALUES 'LEXER:INT (LEXER:INT LEXER:%0))))
;                     ("[:alpha:][:alnum:]*"
;                      (RETURN (VALUES 'TEST-LEXER::NAME LEXER:%0)))
;                     ("[:space:]+"))
; --> PROGN 
; ==>
;   (LEXER::MACROEXPAND-REGEX-EXPR
;    '(REGEX::ALT (REGEX::SEQ (REGEX::REG 0 (REGEX::SEQ # #)) (REGEX::SUCCEED 0))
;      (REGEX::SEQ (REGEX::REG 0 (+ #)) (REGEX::SUCCEED 1))
;      (REGEX::SEQ (REGEX::REG 0 (REGEX::SEQ # #)) (REGEX::SUCCEED 2))
;      (REGEX::SEQ (REGEX::REG 0 (+ #)) (REGEX::SUCCEED 3))))
; 
; caught STYLE-WARNING:
;   undefined function: LEXER::MACROEXPAND-REGEX-EXPR
; 
; compilation unit finished
;   Undefined function:
;     LEXER::MACROEXPAND-REGEX-EXPR
;   caught 1 STYLE-WARNING condition

debugger invoked on a UNDEFINED-FUNCTION in thread
# <THREAD "initial thread" RUNNING {1002998D53}>:

  The function LEXER::MACROEXPAND-REGEX-EXPR is undefined.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [RETRY   ] Retry EVAL of current toplevel form.
  1: [CONTINUE] Ignore error and continue loading file "/home/mgcheung/quicklisp/local-projects/cl-lexer/example.lisp".
  2: [ABORT   ] Abort loading file "/home/mgcheung/quicklisp/local-projects/cl-lexer/example.lisp".
  3:            Exit debugger, returning to top level.

("undefined function")
0]

**Comment by srtlg** [comment]
Please pull commit c857755 it fixes this issue you'll experience when using cl-lexer from current quicklisp
