### ISSUE TITLE
Rename Package

### ISSUE THREAD

**Issue by gluax** [starseeker/cl-lexer#4]
According to ASDF best practices you should rename this project package to be consistent with the naming scheme. As of right now this project shows up as cl-lexer on quickdocs. i.e. the defsystem and exported package should be named cl-lexer to be in line with the project name, or rename the repo to be lexer. As this is causing clashing issues with other packages.

**Comment by starseeker** [comment]
528e6bff6fab061a2994e33f2f6b752a981b3196
